<?php
/**
 * Classe enfant de User
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        User
 */
require_once('User.class.php');

class Administrator extends User {


	/**
	 * Supprime un utilisateur
	 * @access public
	 * @param int $idUser ID de l'utilisateur à supprimer
	 * @return void
	 */

	public  function deleteUser($idUser) {

	}


	/**
	 * Modifie les information d'un utilisateur
	 * @access public
	 * @param array $data Contient les nouvelles informations du profil de l'utilisateur
	 * @return void
	 */

	public  function editProfileUser($data) {

	}


	/**
	 * Envoyer un mail à un utilisateur
	 * @access public
	 * @param array $data Contients les informations du mail
	 * @return void
	 */

	public  function sendMailToOneUser($data) {

	}


	/**
	 * Envoyer un mail à tous les utilisateurs
	 * @access public
	 * @param array $data Contients les informations du mail
	 * @return void
	 */

	public  function sendMailToAllUsers($data) {

	}


}
?>