<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Article {

	/**
	 * 
	 * @var int
	 * @access public
	 */
	public  $idArticle;

	/**
	 * 
	 * @var String
	 * @access public
	 */
	public  $titleArticle;

	/**
	 * 
	 * @var String
	 * @access public
	 */
	public  $contentArticle;


	/**
	 * @access private
	 * @return void
	 */

	private  function __construct() {

	}


	/**
	 * @access public
	 * @param String $name 
	 * @return Multiple
	 */

	public  function __get($name) {

	}


	/**
	 * @access public
	 * @param int $idArticle 
	 * @return Article
	 */

	public  function getArticle($idArticle) {

	}


	/**
	 * @access public
	 * @return Article()
	 */

	public  function getArticles() {

	}


}
?>