<?php
/**
 *
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Article {

	/**
	 *
	 * @var int
	 * @access public
	 */
	public  $idArticle;

	/**
	 *
	 * @var String
	 * @access public
	 */
	public  $titleArticle;

	/**
	 *
	 * @var String
	 * @access public
	 */
	public  $contentArticle;


	/**
	 * @access private
	 * @return void
	 */

	private  function __construct() {

	}


	/**
	 * @access public
	 * @param String $name
	 * @return Multiple
	 */

	public  function __get($name) {

	}


	/**
	 * @access public
	 * @param int $idArticle
	 * @return Article
	 */

	public  function getArticle($idArticle) {

	}


	/**
	 * @access public
	 * @return Article()
	 */

	public static function getArticles() {
		$bdd = MyPDO::getInstance();

		$pdo = $bdd->prepare("SELECT * FROM article");
		$pdo->execute();

		$res = $pdo->fetchAll(PDO::FETCH_CLASS, __CLASS__);

		if(empty($res)){
			return false;
		}

		return $res;
	}

	public static function formRedacArticle($data = array(), $info = "") {

        $title = isset($data['title']) ? $data['title'] : "";
        $content = isset($data['content']) ? $data['content'] : "";
        $category = isset($data['category']) ? $data['category'] : null;

        $categorys = Category::displayArticleCategorys($category);
        $html = <<<HTML
            <script type="text/javascript" src="js/tinymce/tinymce.min.js"></script>
            <script>
                tinymce.init({
                    mode: "specific_textareas",
                    editor_selector: "wysiwyg",
                    language: "fr_FR",
                    height: 200,
                    image_title: true,

                    images_upload_url: 'postAcceptor.php',
                    file_picker_types: 'image',
                    plugins: [
                        "advlist autolink lists link image imagetools charmap preview",
                        "searchreplace  fullscreen",
                        "media table contextmenu paste imagetools textcolor"
                    ],
                    toolbar: "insertfile undo redo | styleselect | forecolor backcolor | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
                    image_advtab: true,
                    file_picker_callback: function(cb, value, meta) {
                        var input = document.createElement('input');
                        input.setAttribute('type', 'file');
                        input.setAttribute('accept', 'image/*');

                        input.onchange = function() {
                          var file = this.files[0];

                          var id = 'blobid' + (new Date()).getTime();
                          var blobCache = tinymce.activeEditor.editorUpload.blobCache;
                          var blobInfo = blobCache.create(id, file);
                          blobCache.add(blobInfo);

                          cb(blobInfo.blobUri(), { title: file.name });
                        };

                        input.click();
                    }
                });
            </script>
            <form action="" method="post">
            $info
                <input type="text" placeholder="Titre de l'article" name="title" value='$title'>
                <textarea class="wysiwyg" name="content">$content</textarea>
                <fieldset>
                    <legend>Catégorie</legend>
                    $categorys
                </fieldset>

                <input type="submit" name="formRedacArticle">
            </form>
HTML;
        return $html;
    }

	public static function addArticle($data){
		$bdd = MyPDO::getInstance();


		$pdo = $bdd->prepare("SELECT * FROM category WHERE idCategory = ?");
		$pdo->execute(array($data['category']));
		$res = $pdo->fetch();

		if(empty($res)){
			return false;
		}

		$pdo = $bdd->prepare("INSERT INTO article VALUES(NULL, ?, ?, ?, ?)");
		$pdo->execute(array($data['title'], $data['content'], $data['category'], $_SESSION['user']->idUser));

		return true;
	}

	public static function displayArticles(){
		$articles = Article::getArticles();

		$html = <<<HTML
		<a href="?a=a">Rédiger un article</a>
		<table>
			<tr>
				<th>Titre</th>
				<th>Catégorie</th>
				<th>Rédacteur</th>
				<th>Modifier</th>
				<th>Supprimer</th>
			</tr>
HTML;

		foreach ($articles as $article) {
			$category = Category::getCategory($article->idCategory);
			$user = User::getUser($article->idUser);
			$html .= <<<HTML
			<tr>
				<td>{$article->titleArticle}</td>
				<td>{$category->lblCategory}</td>
				<td>{$user->nicknameUser}</td>
				<th><a href="?id={$article->idArticle}&a=e">Modifier</a></th>
				<th><a href="?id={$article->idArticle}&a=d">Supprimer</a></th>
			</tr>
HTML;
		}


		$html .= "</table>";

		return $html;
	}


}
?>
