<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Category {

	/**
	 * 
	 * @var int
	 * @access public
	 */
	public  $idCategory;

	/**
	 * 
	 * @var String
	 * @access public
	 */
	public  $lblCategory;

	/**
	 * 
	 * @var int
	 * @access public
	 */
	public  $idCategoryParent;


	/**
	 * @access private
	 * @return void
	 */

	private  function __construct() {

	}


	/**
	 * @access public
	 * @param String $name 
	 * @return Multiple
	 */

	public  function __get($name) {

	}


	/**
	 * @access public
	 * @param int $idCategory 
	 * @return Category
	 */

	public  function getCategory($idCategory) {

	}


	/**
	 * @access public
	 * @return Category()
	 */

	public  function getCategorys() {

	}


}
?>