<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Comment {

	/**
	 * 
	 * @var int
	 * @access public
	 */
	public  $idComment;

	/**
	 * 
	 * @var String
	 * @access public
	 */
	public  $contentComment;

	/**
	 * 
	 * @var int
	 * @access public
	 */
	public  $idUser;

	/**
	 * 
	 * @var 
	 * @access public
	 */
	public  $idArticle;


	/**
	 * @access private
	 * @return void
	 */

	private  function __construct() {

	}


	/**
	 * @access public
	 * @param String $name 
	 * @return Multiple
	 */

	public  function get($name) {

	}


	/**
	 * @access public
	 * @param int $idComment 
	 * @return Comment
	 */

	public  function getComment($idComment) {

	}


	/**
	 * @access public
	 * @return Comment()
	 */

	public  function getComments() {

	}


}
?>