<?php
/**
 *
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class PrivateMessage {

	/**
	 *
	 * @var int
	 * @access public
	 */
	public  $idPM;

	/**
	 *
	 * @var String
	 * @access public
	 */
	public  $titlePM;

	/**
	 *
	 * @var String
	 * @access public
	 */
	public  $contentPM;

	/**
	 *
	 * @var Datetime
	 * @access public
	 */
	public  $datetimePM;

	public $isRead;

	/**
	 *
	 * @var int
	 * @access public
	 */
	public  $idSender;

	/**
	 *
	 * @var
	 * @access public
	 */
	public  $idReceiver;


	/**
	 * @access private
	 * @return void
	 */

	private  function __construct() {

	}


	/**
	 * @access public
	 * @param String $name
	 * @return Multiple
	 */

	public  function __get($name) {
		if(property_exists(__CLASS__, $name)){
			return $this->$name;
		}
		throw new Exception("L'attribut {$name} n'existe pas");
	}


	/**
	 * @access public
	 * @param int $idPM
	 * @return PrivateMessage
	 */

	public static function getPM($idPM) {
		$bdd = MyPDO::getInstance();
		$pdo = $bdd->prepare("SELECT * FROM privatemessage WHERE idPM = ?");
		$pdo->setFetchMode(PDO::FETCH_CLASS, __CLASS__);
		$pdo->execute(array($idPM));

		$PM = $pdo->fetch();

		if(empty($PM)){
			return false;
		}

		return $PM;
	}


	/**
	 * @access public
	 * @return PrivateMessage()
	 */

	public static function getPMsReceiv($idUser) {
		$bdd = MyPDO::getInstance();
		$pdo = $bdd->prepare("SELECT * FROM privatemessage WHERE idReceiver = ?");
		$pdo->setFetchMode(PDO::FETCH_CLASS, __CLASS__);
		$pdo->execute(array($idUser));

		$PM = $pdo->fetchAll();

		if(empty($PM)){
			return false;
		}

		return $PM;
	}

	public static function getPMsSend($idUSer) {
		$bdd = MyPDO::getInstance();
		$pdo = $bdd->prepare("SELECT * FROM privatemessage WHERE idSender = ?");
		$pdo->setFetchMode(PDO::FETCH_CLASS, __CLASS__);
		$pdo->execute(array($idUser));

		$PM = $pdo->fetchAll();

		if(empty($PM)){
			return false;
		}

		return $PM;
	}

	public static function sendPM($data){
		$bdd = MyPDO::getInstance();

		$user = User::getUserByNickName($data['receiver']);
		if(!$user){
			return false;
		}

		$pdo = $bdd->prepare("INSERT INTO privateMessage VALUES(NULL, ? , ?, NOW(), 0, ?, ?)");
		$pdo->execute(array(htmlentities($data['title']), htmlentities($data['content']), $_SESSION['user']->idUser, $user->idUser));

		return true;
	}

	public static function displayPMs($PMs) {
		$html = <<<HTML
		<div class="table-responsive">
			<table class="table table-bordered table-striped">
				<tr>
					<th>Objet</th>
					<th>Expéditeur</th>
					<th>Date de réception</th>
				</tr>
HTML;

		foreach ($PMs as $pm) {
			$sender = User::getUser($pm->idSender);
            $datetime = strftime("le %d/%m/%Y à %T ", strtotime($pm->datetimePM));
            $style = $pm->isRead ? "style='color:blue'" : "style='color:green'";
			$html .= <<<HTML
			<tr>
				<td><a $style href="?id={$pm->idPM}">{$pm->titlePM}</a></td>
				<td>{$sender->nicknameUser}</td>
				<td>$datetime</td>
			</tr>
HTML;
		}

		$html .= "</table></div>";

		return $html;
	}

	public function displayPM(){
		$content = nl2br($this->contentPM);
		$sender = User::getUser($this->idSender);
        $datetime = strftime("le %d/%m/%Y à %T ", strtotime($this->datetimePM));
		$html = <<<HTML
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">
						<h4>{$this->titlePM}</h4>
					</div>
                    <div class="panel-body">
                    	$content
                    </div>
                    <div class="panel-footer text-right">
                    	Envoyé $datetime par {$sender->nicknameUser}
                    </div>
                </div>
		</div>
HTML;
		return $html;
	}

	public function setIsRead(){
		$bdd = MyPDO::getInstance();

		$pdo = $bdd->prepare("UPDATE privatemessage SET isRead = 1 WHERE idPM = ?");
		$pdo->execute(array($this->idPM));

		return true;
	}
}
?>
