<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class PrivateMessage {

	/**
	 * 
	 * @var int
	 * @access public
	 */
	public  $idPM;

	/**
	 * 
	 * @var String
	 * @access public
	 */
	public  $titlePM;

	/**
	 * 
	 * @var String
	 * @access public
	 */
	public  $contentPM;

	/**
	 * 
	 * @var Datetime
	 * @access public
	 */
	public  $datetimePM;

	/**
	 * 
	 * @var int
	 * @access public
	 */
	public  $idSender;

	/**
	 * 
	 * @var 
	 * @access public
	 */
	public  $idReceiver;


	/**
	 * @access private
	 * @return void
	 */

	private  function __construct() {

	}


	/**
	 * @access public
	 * @param String $name 
	 * @return Multiple
	 */

	public  function __get($name) {

	}


	/**
	 * @access public
	 * @param int $idPM 
	 * @return PrivateMessage
	 */

	public  function getPM($idPM) {

	}


	/**
	 * @access public
	 * @return PrivateMessage()
	 */

	public  function getPMs() {

	}


}
?>