<?php
/**
 *
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class User {

	/**
	 * ID de l'utilisateur
	 * @var int
	 * @access protected
	 */
	protected  $idUser;

	/**
	 * Pseudo de l'utilisateur
	 * @var String
	 * @access protected
	 */
	protected  $nicknameUser;

	/**
	 * E-mail de l'utilisateur
	 * @var String
	 * @access protected
	 */
	protected  $emailUser;

	protected $validUser;

	protected $resetPasswordUser;

	protected $deleteUser;

	/**
	 * Autorisation écriture d'un article
	 * @var Bool
	 * @access protected
	 */
	protected  $redacArticle;

	/**
	 * Autorisation modification de ses articles
	 * @var Bool
	 * @access protected
	 */
	protected  $editOwnArticle;

	/**
	 * Autorisation suppression de ses articles
	 * @var Bool
	 * @access protected
	 */
	protected  $deleteOwnArticle;

	/**
	 * Autorisation d'édition des commentaires des autres utilisateurs
	 * @var Bool
	 * @access protected
	 */
	protected  $editComment;

	/**
	 * Autorisation de suppression des commentaires des autres utilisateurs
	 * @var Bool
	 * @access protected
	 */
	protected  $deleteComment;

	protected $isAdministrator;


	/**
	 * Fonction __construct privée car PDO s'occupe de l'instanciation
	 * @access private
	 * @return void
	 */

	private  function __construct() {

	}


	/**
	 * Accesseur
	 * @access public
	 * @param String $name Nom de l'attribut
	 * @return Multiple
	 */

	public  function __get($name) {
		if(property_exists(__CLASS__, $name)){
			return $this->$name;
		}
		throw new NotAttributeException("L'attribut {$name} n'existe pas");
	}

	public function __set($name, $value){
        if(property_exists(__CLASS__, $name)){
            $this->$name = $value;
        } else {
            return "Attribut inexistant";
        }
    }

    public static function getUser($idUser) {
        $bdd = MyPDO::getInstance();

        $pdo = $bdd->prepare("SELECT * FROM user WHERE idUser = ?");
        $pdo->execute(array($idUser));
        $pdo->setFetchMode(PDO::FETCH_CLASS, __CLASS__);

        $res = $pdo->fetch();

        if(empty($res)){
            return false;
        }

        return $res;
    }

    public static function getUserByNickName($nicknameUser) {
        $bdd = MyPDO::getInstance();

        $pdo = $bdd->prepare("SELECT * FROM user WHERE nicknameUser = ?");
        $pdo->execute(array($nicknameUser));
        $pdo->setFetchMode(PDO::FETCH_CLASS, __CLASS__);

        $res = $pdo->fetch();

        if(empty($res)){
            return false;
        }

        return $res;
    }

    public static function getUsers() {
        $bdd = MyPDO::getInstance();

        $pdo = $bdd->prepare("SELECT * FROM user");
        $pdo->execute();
        $pdo->setFetchMode(PDO::FETCH_CLASS, __CLASS__);

        $res = $pdo->fetchAll();

        if(empty($res)){
            return false;
        }

        return $res;
    }

    public static function listUsers(){
        $users = self::getUsers();

        $html = <<<HTML
        <table>
            <tr>
                <th>ID de l'utilisateur</th>
                <th>Pseudo</th>
                <th>E-mail</th>
                <th>Modfier</th>
                <th>Supprimer</th>
            </tr>
HTML;

        foreach ($users as $user) {
            $html .= <<<HTML
            <tr>
                <td>{$user->idUser}</td>
                <td>{$user->nicknameUser}</td>
                <td>{$user->emailUser}</td>
                <td><a href=?id={$user->idUser}&a=e>Modifier</a></td>
                <td><a href=?id={$user->idUser}&a=d>Supprimer</a></td>
            </tr>
HTML;
        }

        $html .= "</table>";
        return $html;
    }

	public static function formConnection($infos = "", $data = array()){
		$nickname = isset($data['nickname']) ? $data['nickname'] : "";
		$html = <<<HTML
			<form action="" method="post">
				$infos
				<input type="text" placeholder="Pseudo" name="nickname" value="$nickname" required>
				<input type="password" placeholder="Mot de passe" name="password" required>
				<input type="submit" value="Se connecter" name="formConnection">
				<a href="resetPassword.php">Mot de passe oublié ?</a>
			</form>
HTML;
		return $html;
	}


	/**
	 * Vérifie l'existence de l'utilisateur et retourne une instance de User s'il existe
	 * @access public
	 * @param array $data Contient les informations pour se connecter
	 * @return User
	 */

	public static  function createFromAuth($data) {
		$pdo = MyPDO::getInstance();
		if(empty($data['nickname']) || empty($data['password'])){
			return false;
		}
		$login = $pdo->prepare( 'SELECT idUser, nicknameUser, emailUser, validUser, redacArticle, editOwnArticle, deleteOwnArticle, editComment, deleteComment, isAdministrator
								FROM user
								WHERE nicknameUser = ? AND passwordUser = ?');
		$login->execute(array($data['nickname'], hash("sha256", $data['password'])));
		$login->setFetchMode(PDO::FETCH_CLASS, __CLASS__);
		$res = $login->fetch();
		if(empty($res)){
			return false;
		} elseif(!is_null($res->validUser)){
			return "Votre compte n'a pas été validé";
		} else {
			if($res->isAdministrator){
				$res = new Administrator($res);
			}
			self::startSession();
			$_SESSION['connected'] = true;
			return $res;
		}
	}


	/**
	 * Démarre une session si ce n'est pas encore fait
	 * @access public
	 * @return void
	 */

	public static  function startSession() {
		/*if(headers_sent()){
			throw new Exception("Vous êtes déjà connecté");
		}*/
		if(!session_id()){
			session_start();
		}
	}


	/**
	 * Linéarise l'utilisateur en l'enregistrant dans une variable de session
	 * @access public
	 * @return void
	 */

	public  function saveIntoSession() {
		self::startSession();
		$_SESSION['user'] = $this;
	}


	/**
	 * Délinéarisation de l'utilisateur
	 * @access public
	 * @return User
	 */

	public static  function createFromSession() {
		self::startSession();
		if (isset($_SESSION['user'])){
			$u = $_SESSION['user'];
			return $u;
		}
	}


	/**
	 * Vérifie si l'utilisateur est connecté
	 * @access public
	 * @return Bool
	 */

	public static  function isConnected() {
		try{
			self::startSession();
			if (isset($_SESSION['connected']) && $_SESSION['connected']) {
				return true;
			}
		} catch(SessionException $e){
			return "Échec d'authentification&nbsp;: {$e->getMessage()}";
		}
	}

	/**
	 * Déconnecte l'utilisateur
	 * @access public
	 * @return void
	 */

	public static  function logout() {
		self::startSession();
		session_destroy();
		unset($_SESSION);
	}


	public static function formAddUser($infos = array(), $data = null){
		$nickname = isset($data['nickname']) ? $data['nickname'] : "";
		$email = isset($data['email']) ? $data['email'] : "";

		$displayInfos = "";
		if(sizeof($infos) > 0){
			$displayInfos = "<div>" . implode("<br>", $infos) . "</div>";
		}
		$html = <<<HTML
			<form action="" method="post">
				$displayInfos
			 	<input type="text" placeholder="Pseudo" name="nickname" value="$nickname" pattern=".{5,20}" required>
			 	<input type="password" placeholder="Mot de passe" name="password" pattern=".{8,}" required>
			 	<input type="email" placeholder="Adresse e-mail" name="email" value="$email" required>
			 	<input type="submit" value="S'inscrire" name="formAdd">
			</form>
HTML;
		return $html;
	}

	/**
	 * Inscrit un utilisateur
	 * @access public
	 * @param array $data Contient les informations pour l'inscription
	 * @return void
	 */

	public static  function addUser($data) {
		if(!isset($data['nickname']) || empty($data['nickname']) || !isset($data['password']) || empty($data['password']) || !isset($data['email']) || empty($data['email']))
			return "Tous les champs sont requis";

		$erreurs = array();


		$data['nickname'] = filter_var($data['nickname'], FILTER_SANITIZE_SPECIAL_CHARS);

		if(strlen($data['nickname']) < 5 || strlen($data['nickname']) > 20)
			$erreurs[] = "Le pseudo doit faire entre 5 et 20 caractères";

		if(strlen($data['password']) < 8)
			$erreurs[] = "Le mot de passe doit contenir au moins 8 caractères";

		if(filter_var($data['email'], FILTER_VALIDATE_EMAIL) === false)
		    $erreurs[] = "L'adresse e-mail n'est pas valide";

		if(sizeof($erreurs) > 0)
			return $erreurs;

		$bdd = MyPDO::getInstance();

		$pdo = $bdd->prepare("SELECT * FROM user WHERE nicknameUser = ?");
		$pdo->execute(array($data['nickname']));
		$pseudo = $pdo->fetch();

		if($pseudo)
			$erreurs[] = "Le pseudo est déjà utilisé";

		$pdo = $bdd->prepare("SELECT * FROM user WHERE emailUser = ?");
		$pdo->execute(array($data['email']));
		$email = $pdo->fetch();

		if($email)
			$erreurs[] = "L'adresse e-mail est déjà utilisée";

		if(sizeof($erreurs) > 0)
			return $erreurs;

        $validCode = md5(uniqid());
		$pdo = $bdd->prepare("INSERT INTO USER VALUES(NULL, ?, ?, ?, ?, NULL, NULL, 0, 0, 0, 0, 0, 0)");
		$pdo->execute(array($data['nickname'], $data['email'], hash('sha256', $data['password']), $validCode));

        self::validMail($data['email'], $validCode);

		return true;
	}

	public static function validMail($email, $validCode){

        $site = Site::getOptions();
		$boundary = "-----=".md5(rand());

    	$header = "From: " . $site['adminEmail'] . "\n";
    	$header.= "Reply-to: " . $site['adminEmail'] ."\n";
    	$header.= "MIME-Version: 1.0\n";
    	$header.= "Content-Type: multipart/alternative;\n boundary=" . $boundary . "\n";

    	$message = "\n--" . $boundary . "\n";
    	$message .= "Content-Type: text/html; charset=\"ISO-8859-1\"\n";
		$message .= "Content-Transfer-Encoding: 8bit\n";
        $message .= "\nBienvenue sur " . $site['siteName'] . "\n<br><br>";
        $message .= "\nPour valider votre inscription, <a href='" . $site['urlSite'] . "verif.php?action=valid&email=" . $email . "&code=" . $validCode . "'>cliquez-ici</a>\n<br><br>";
        $message .= "\nSi vous ne pouvez pas cliquer, copiez/collez le lien suivant: " . $site['urlSite'] . "verif.php?action=valid&email=" . $email . "&code=" . $validCode . "\n\n";
		$message .= "\n--" . $boundary . "--\n";
		return mail($email, "[" . $site['siteName'] . "] Validation de l'e-mail", $message, $header);
	}

    public static function verifCode($data){
        $bdd = MyPDO::getInstance();

        if($data['action'] == "valid"){
        	$code = "validUser";
        } elseif($data['action'] == "resetPW"){
        	$code = "resetPasswordUser";
        } elseif($data['action'] == "delete") {
        	$code = "deleteUser";
        } else {
        	return false;
        }
        $pdo = $bdd->prepare("SELECT idUser FROM user WHERE emailUser = ? AND $code = ?");
        $pdo->execute(array($data['email'], $data['code']));
        $res = $pdo->fetch();

        if(empty($res)){
            return false;
        } else {
        	if($code = "validUser"){
	            $pdo = $bdd->prepare("UPDATE user SET $code = null WHERE idUser = ?");
	            $pdo->execute(array($res['idUser']));
	        }
	        return true;
        }
    }

    public static function formResetPasswordEmail($email = ""){
    	$info = !empty($email) ? "L'adresse e-mail n'est pas valide" : "";
    	$html = <<<HTML
    		<form action="" method="post">
    			$info
    			<p>Veuillez saisir votre adresse e-mail. Un lien permettant de créer un nouveau mot de passe vous sera envoyé par e-mail.</p>
    			<input type="email" name="email" value="$email" required>
    			<input type="submit" name="formResetPasswordEmail">
    		</form>
HTML;
		return $html;
    }


    public static function resetPasswordEmail($email){

        $resetCode = md5(uniqid());
        $bdd = MyPDO::getInstance();
        $pdo = $bdd->prepare("SELECT nicknameUser FROM user WHERE emailUser = ?");
        $pdo->execute(array($email));
        $res = $pdo->fetch();
        if(empty($res)){
        	return false;
        }

        $pdo = $bdd->prepare("UPDATE user SET resetPasswordUser = ? WHERE nicknameUser = ?");
        $pdo->execute(array($resetCode, $res['nicknameUser']));

        $nicknameUser = $res['nicknameUser'];

        $site = Site::getOptions();
		$boundary = "-----=".md5(rand());

    	$header = "From: " . $site['adminEmail'] . "\n";
    	$header.= "Reply-to: " . $site['adminEmail'] ."\n";
    	$header.= "MIME-Version: 1.0\n";
    	$header.= "Content-Type: multipart/alternative;\n boundary=" . $boundary . "\n";

    	$message = "\n--" . $boundary . "\n";
    	$message .= "Content-Type: text/html; charset=\"UTF-8\"\n";
		$message .= "Content-Transfer-Encoding: 8bit\n";
        $message .= "\nBonjour, \n<br>";
        $message .= "\nQuelqu’un a demandé la réinitialisation du mot de passe pour le compte suivant : $nicknameUser\n\n<br><br>";
        $message .= "\nS’il s’agit d’une erreur, ignorez ce message et la demande ne sera pas prise en compte.\n\n<br><br>";
        $message .= "\nPour renouveler votre mot de passe, <a href='" . $site['urlSite'] . "verif.php?action=resetPW&email=" . $email . "&code=" . $resetCode . "'>cliquez-ici</a>\n<br><br>";
        $message .= "\nSi vous ne pouvez pas cliquer, copiez/collez le lien suivant: " . $site['urlSite'] . "verif.php?action=resetPW&email=" . $email . "&code=" . $resetCode . "\n\n";
		$message .= "\n--" . $boundary . "--\n";
		return mail($email, "[" . $site['siteName'] . "] Oubli de mot de passe", $message, $header);
	}

	public static function formResetPassword($info = ""){
		if(isset($_GET['email']) && isset($_GET['code'])){
			$email = $_GET["email"];
			$code = $_GET["code"];
			$html = <<<HTML
			<form action="" method="post">
				$info
				<input type="password" name="password" placeholder="Mot de passe (min: 8 car.)" pattern=".{8,}" required>
				<input type="submit" name="formResetPassword" value="Modifier">
				<input type="hidden" name="email" value="$email">
				<input type="hidden" name="code" value="$code">
			</form>
HTML;

			return $html;
		} else {
			return false;
		}
	}

	public static function updateResetPassword($data){
		if(strlen($data['password']) < 8){
			return false;
		}
		$bdd = MyPDO::getInstance();

        $pdo = $bdd->prepare("UPDATE user SET passwordUser = ?, resetPasswordUser = null WHERE emailUser = ?");
        $pdo->execute(array(hash('sha256', $data['password']), $data['email']));
        return true;
	}

	public function formEditEmail($email = "", $info = ""){
		$email = empty($email) ? $this->emailUser : $email;
		$html = <<<HTML
			<form action="" method="post">
				$info
			 	<input type="email" placeholder="E-mail" name="email" value="$email" required>
			 	<input type="submit" value="Modifier" name="formEditEmail">
			</form>
HTML;
		return $html;
	}

	/**
	 * Editer son profil
	 * @access public
	 * @param array $data Contient les nouvelles informations du profil
	 * @return void
	 */

	public  function editEmail($email) {
		if($this->emailUser == $email)
			return true;

		if(filter_var($email, FILTER_VALIDATE_EMAIL) === false)
		    return false;

		$bdd = MyPDO::getInstance();
		$pdo = $bdd->prepare("SELECT emailUser FROM user WHERE emailUser = ?");
		$pdo->execute(array($email));
		$res = $pdo->fetch();
		if($res){
			return -1;
		}
		$pdo = $bdd->prepare("UPDATE user SET emailUser = ? WHERE idUser = ?");
		$pdo->execute(array($email, $this->idUser));
        $this->emailUser = $email;
        $_SESSION['user']->emailUser = $this->emailUser;
		return true;
	}

	public function formDeleteUser($info = ""){
		$html = <<<HTML
			<p>Supprimer mon compte:</p>
			<form action="" method="post">
				$info
				<input type="password" name="password" placeholder="Mot de passe" required>
				<input type="submit" name="formDeleteUser" value="Supprimer mon compte">
			</form>
HTML;
		return $html;
	}

	public function deleteUser($password){
		$bdd = MyPDO::getInstance();

		$pdo = $bdd->prepare("SELECT passwordUser FROM user WHERE idUser = ? AND passwordUser = ?");
		$pdo->execute(array($this->idUser, hash("sha256", $password)));
		$res = $pdo->fetch();

		if(empty($res)){
			return false;
		}

		$this->deleteUser = md5(uniqid());
		$_SESSION['user']->deleteUser = $this->deleteUser;
		$pdo = $bdd->prepare("UPDATE user SET deleteUser = ? WHERE idUser = ?");
		$pdo->execute(array($this->deleteUser, $this->idUser));

		return true;
	}

	public function deleteUserEmail(){
        $site = Site::getOptions();
		$boundary = "-----=".md5(rand());

    	$header = "From: " . $site['adminEmail'] . "\n";
    	$header.= "Reply-to: " . $site['adminEmail'] ."\n";
    	$header.= "MIME-Version: 1.0\n";
    	$header.= "Content-Type: multipart/alternative;\n boundary=" . $boundary . "\n";

    	$message = "\n--" . $boundary . "\n";
    	$message .= "Content-Type: text/html; charset=\"UTF-8\"\n";
		$message .= "Content-Transfer-Encoding: 8bit\n";
        $message .= "\nBonjour, \n<br>";
        $message .= "\nQuelqu’un a demandé la suppression du compte suivant : $this->nicknameUser\n\n<br><br>";
        $message .= "\nS’il s’agit d’une erreur, ignorez ce message et la demande ne sera pas prise en compte.\n\n<br><br>";
        $message .= "\nPour supprimer votre compte, <a href='" . $site['urlSite'] . "verif.php?action=delete&email=" . $this->emailUser . "&code=" . $this->deleteUser . "'>cliquez-ici</a>\n<br><br>";
        $message .= "\nSi vous ne pouvez pas cliquer, copiez/collez le lien suivant: " . $site['urlSite'] . "verif.php?action=delete&email=" . $this->emailUser . "&code=" . $this->deleteUser . "\n\n";
		$message .= "\n--" . $boundary . "--\n";
		return mail($this->emailUser, "[" . $site['siteName'] . "] Suppression de compte", $message, $header);

	}

	public static function validDeleteUser($email){
		$bdd = MyPDO::getInstance();
		$pdo = $bdd->prepare("SELECT isAdministrator FROM user WHERE emailUser = ?");
		$pdo->execute(array($email));
		$res = $pdo->fetch();

		if($res['isAdministrator']){
			return false;
		}

		$pdo = $bdd->prepare("DELETE FROM user WHERE emailUser = ?");
		$pdo->execute(array($email));

		return true;
	}

    public function formSendPM($data = array(), $info = ""){
        $receiver = isset($data['receiver']) ? $data['receiver'] : "";
        $title = isset($data['title']) ? $data['title'] : "";
        $content = isset($data['content']) ? $data['content'] : "";

        $html = <<<HTML
        <form action="" method="post">
            $info
            <input type="text" name="receiver" value="$receiver" placeholder="Destinataire">
            <input type="text" name="title" value="$title" placeholder="Objet">
            <textarea name="content">$content</textarea>
            <input type="submit" name="formSendPM">
        </form>
HTML;

        return $html;
    }

    public function formReplyPM($data = array(), $info = ""){
        $title = isset($data['title']) ? $data['title'] : "RE: " . $data['defaultTitle'];
        $content = isset($data['content']) ? $data['content'] : "";

        $html = <<<HTML
        <form action="" method="post">
            $info
            <input type="text" name="title" value="$title" placeholder="Objet">
            <textarea name="content">$content</textarea>
            <input type="submit" name="formReplyPM" value="Répondre">
        </form>
HTML;

        return $html;
    }

}
?>
