<?php
/**
 *
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

require_once('User.class.php');

class WebPage {

	/**
	 *
	 * @var String
	 * @access private
	 */
	private  $head = null;

	/**
	 *
	 * @var String
	 * @access private
	 */
	private  $title = null;

	/**
	 *
	 * @var String
	 * @access private
	 */
	private  $body = null;

    private  $menu = null;


	/**
	 * @access public
	 * @param String $title
	 * @return void
	 */

	public  function __construct($title = null, $menu = true) {
		$this->setTitle($title);
        if($menu){
            $this->setMenu();
            $this->setCss();
            $this->setJs();
        }
        else{
            $this->setAdminMenu();
            $this->setCss(true);
            $this->setJs(true);
        }
	}


	/**
	 * @access public
	 * @param String $title
	 * @return String
	 */

	public  function setTitle($title) {
        $this->title = $title;
	}


	/**
	 * @access public
	 * @param String $content
	 * @return void
	 */

	public  function appendToHead($content) {
        $this->head .= $content;
	}


	/**
	 * @access public
	 * @param String $css
	 * @return void
	 */

	public  function appendCss($css) {
		$this->appendToHead(<<<HTML
    <style type='text/css'>
    $css
    </style>
HTML
);
	}


	/**
	 * @access public
	 * @param String $url
	 * @return void
	 */

	public  function appendCssUrl($url) {
		$this->appendToHead(<<<HTML
    <link rel="stylesheet" type="text/css" href="{$url}">
HTML
);
	}


	/**
	 * @access public
	 * @param String $js
	 * @return void
	 */

	public  function appendJs($js) {
        $this->appendToHead(<<<HTML
    <script type='text/javascript'>
    $js
    </script>

HTML
);
	}


	/**
	 * @access public
	 * @param String $url
	 * @return void
	 */

	public  function appendJsUrl($url) {
		$this->appendToHead(<<<HTML
    <script type='text/javascript' src='$url'></script>

HTML
        );
	}


	/**
	 * @access public
	 * @param String $content
	 * @return void
	 */

	public  function appendContent($content) {
		$this->body .= $content;
	}

    public function setCss($admin = false){
        $siteOptionsTheme = Site::getOptions()['theme'];
        if($admin)
            $path = "../" . "style/" . $siteOptionsTheme . "/";
        else
            $path = "style/" . $siteOptionsTheme . "/";
        $files = parse_ini_file($path . "files.ini");
        if(array_key_exists('css', $files)){
            $filesCss = parse_ini_file($path . "files.ini")['css'];
            if(!is_null($filesCss)){
                foreach ($filesCss as $fileCss) {
                    $this->appendCssUrl($path . $fileCss);
                }
            }
        }
    }

    public function setJs($admin = false){
        $siteOptionsTheme = Site::getOptions()['theme'];
        if($admin)
            $path = "../" . "style/" . $siteOptionsTheme . "/";
        else
            $path = "style/" . $siteOptionsTheme . "/";
        $files = parse_ini_file($path . "files.ini");
        if(array_key_exists('js', $files)){
            $filesJs = $files['js'];
            if(!is_null($filesJs)){
                foreach ($filesJs as $fileJs) {
                    $this->appendCssUrl($path . $fileJs);
                }
            }
        }
    }

    public function setMenu(){
        User::startSession();
        $categorys = Category::displayMenuCategorys();
        if(isset($_SESSION['connected']) && $_SESSION['connected']){
            if($_SESSION["user"]->isAdministrator || $_SESSION['user']->redacArticle || $_SESSION['user']->editOwnArticle || $_SESSION['user']->deleteOwnArticle || $_SESSION['user']->editComment || $_SESSION['user']->deleteComment){
            $this->menu = <<<HTML
        <ul>
            <li><a href="index.php">Accueil</a></li>
            $categorys
            <li><a href="privatemessages.php">Messages</a></li>
            <li><a href="forum.php">Forum</a></li>
            <li><a href="profile.php">Profil</a></li>
            <li><a href="administration/index.php">Administration</a></li>
            <li><a href="contact.php">Contact</a></li>
            <li><a href="logout.php">Déconnexion</a></li>
        </ul>
HTML;
            } else {
            $this->menu = <<<HTML
        <ul>
            <li><a href="index.php">Accueil</a></li>
            $categorys
            <li><a href="privatemessages.php">Messages</a></li>
            <li><a href="forum.php">Forum</a></li>
            <li><a href="profile.php">Profil</a></li>
            <li><a href="contact.php">Contact</a></li>
            <li><a href="logout.php">Déconnexion</a></li>
        </ul>
HTML;
            }
        } else {
            $this->menu = <<<HTML
        <ul>
            <li><a href="index.php">Accueil</a></li>
            $categorys
            <li><a href="forum.php">Forum</a></li>
            <li><a href="connexion.php">Connexion</a></li>
            <li><a href="subscribe.php">Inscription</a></li>
            <li><a href="contact.php">Contact</a></li>
        </ul>
HTML;
        }
    }

    public function setAdminMenu(){
        User::startSession();
        if(isset($_SESSION['connected']) && $_SESSION['connected']){
            $html = "<ul>";
            $html .= "<li><a href='..'>Site</a></li>\n";
            if($_SESSION['user']->redacArticle || $_SESSION['user']->editOwnArticle || $_SESSION['user']->deleteOwnArticle || $_SESSION['user']->editComment || $_SESSION['user']->deleteComment){
                $html .= "<li><a href='articles.php'>Articles</a></li>\n";
            }

            if($_SESSION['user']->isAdministrator){
                $html .= "<li><a href='categorys.php'>Catégories</a></li>\n";
                $html .= "<li><a href='users.php'>Membres</a></li>\n";
            }

            if($_SESSION['user']->isAdministrator){
                $html .= "<li><a href='optionsSite.php'>Options</a></li>\n";
            }

            $html .= "</ul>";

            $this->menu = $html;
        }

    }


	/**
	 * @access public
	 * @return String
	 */

	public  function toHTML() {
        if (is_null($this->title)) {
            throw new Exception(__CLASS__ . ": title not set") ;
        }
        return <<<HTML
<!doctype html>
<html lang="fr">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>{$this->title}</title>
        {$this->head}
    </head>
    <body>
        {$this->menu}
        {$this->body}
    </body>
</html>
HTML;
	}


}
?>
