<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class WebPage {

	/**
	 * 
	 * @var String
	 * @access private
	 */
	private  $head = null;

	/**
	 * 
	 * @var String
	 * @access private
	 */
	private  $title = null;

	/**
	 * 
	 * @var String
	 * @access private
	 */
	private  $body = null;


	/**
	 * @access public
	 * @param String $title 
	 * @return void
	 */

	public  function __construct($title = null) {

	}


	/**
	 * @access public
	 * @param String $title 
	 * @return String
	 */

	public  function setTitle($title) {

	}


	/**
	 * @access public
	 * @param String $content 
	 * @return void
	 */

	public  function appendToHead($content) {

	}


	/**
	 * @access public
	 * @param String $css 
	 * @return void
	 */

	public  function appendCss($css) {

	}


	/**
	 * @access public
	 * @param String $url 
	 * @return void
	 */

	public  function appendCssUrl($url) {

	}


	/**
	 * @access public
	 * @param String $js 
	 * @return void
	 */

	public  function appendJs($js) {

	}


	/**
	 * @access public
	 * @param String $url 
	 * @return void
	 */

	public  function appendJsUrl($url) {

	}


	/**
	 * @access public
	 * @param String $content 
	 * @return void
	 */

	public  function appendContent($content) {

	}


	/**
	 * @access public
	 * @return String
	 */

	public  function toHTML() {

	}


}
?>