<?php
/**
 *
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

require_once('User.class.php');

class WebPage {

	/**
	 *
	 * @var String
	 * @access private
	 */
	private  $head = null;

	/**
	 *
	 * @var String
	 * @access private
	 */
	private  $title = null;

	/**
	 *
	 * @var String
	 * @access private
	 */
	private  $body = null;

    private  $menu = null;

    private $footer = null;


	/**
	 * @access public
	 * @param String $title
	 * @return void
	 */

	public  function __construct($title = null, $menu = true) {
		$this->setTitle($title);
        $this->setFooter();
        if($menu){
            $this->setMenu();
            $this->setCss();
            $this->setJs();
        }
        else{
            $this->setAdminMenu();
            $this->setCss(true);
            $this->setJs(true);
        }
	}


	/**
	 * @access public
	 * @param String $title
	 * @return String
	 */

	public  function setTitle($title) {
        $this->title = $title;
	}


	/**
	 * @access public
	 * @param String $content
	 * @return void
	 */

	public  function appendToHead($content) {
        $this->head .= $content;
	}


	/**
	 * @access public
	 * @param String $css
	 * @return void
	 */

	public  function appendCss($css) {
		$this->appendToHead(<<<HTML
    <style type='text/css'>
    $css
    </style>
HTML
);
	}


	/**
	 * @access public
	 * @param String $url
	 * @return void
	 */

	public  function appendCssUrl($url) {
		$this->appendToHead(<<<HTML
    <link rel="stylesheet" type="text/css" href="{$url}">
HTML
);
	}


	/**
	 * @access public
	 * @param String $js
	 * @return void
	 */

	public  function appendJs($js) {
        $this->appendToHead(<<<HTML
    <script type='text/javascript'>
    $js
    </script>

HTML
);
	}


	/**
	 * @access public
	 * @param String $url
	 * @return void
	 */

	public  function appendJsUrl($url) {
		$this->appendToHead(<<<HTML
    <script type='text/javascript' src='$url'></script>

HTML
        );
	}


	/**
	 * @access public
	 * @param String $content
	 * @return void
	 */

	public  function appendContent($content) {
		$this->body .= $content;
	}

    public function setCss($admin = false){
        $siteOptionsTheme = Site::getOptions()['theme'];
        if($admin)
            $path = "../" . "style/" . $siteOptionsTheme . "/";
        else
            $path = "style/" . $siteOptionsTheme . "/";
        if(file_exists($path . "files.ini")){
            $files = parse_ini_file($path . "files.ini");
            if(array_key_exists('css', $files)){
                $filesCss = parse_ini_file($path . "files.ini")['css'];
                if(!is_null($filesCss)){
                    foreach ($filesCss as $fileCss) {
                        $this->appendCssUrl($path . $fileCss);
                    }
                }
            }
        }
    }

    public function setJs($admin = false){
        $siteOptionsTheme = Site::getOptions()['theme'];
        if($admin)
            $path = "../" . "style/" . $siteOptionsTheme . "/";
        else
            $path = "style/" . $siteOptionsTheme . "/";
        if(file_exists($path . "files.ini")){
            $files = parse_ini_file($path . "files.ini");
            if(array_key_exists('js', $files)){
                $filesJs = $files['js'];
                if(!is_null($filesJs)){
                    foreach ($filesJs as $fileJs) {
                        $this->appendJsUrl($path . $fileJs);
                    }
                }
            }
        }
    }

    public function setMenu(){
        User::startSession();
        $categorys = Category::displayMenuCategorys();
        $site = Site::getOptions();
        $this->menu = <<<HTML
        <nav class="navbar navbar-default">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">{$site['siteName']}</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="index.php">{$site['siteName']}</a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
HTML;
        if(isset($_SESSION['connected']) && $_SESSION['connected']){
            if($_SESSION["user"]->isAdministrator || $_SESSION['user']->redacArticle || $_SESSION['user']->editOwnArticle || $_SESSION['user']->deleteOwnArticle || $_SESSION['user']->editComment || $_SESSION['user']->deleteComment){
            $this->menu .= <<<HTML
            <li><a href="index.php">Accueil</a></li>
            $categorys
            <li><a href="privatemessages.php">Messages</a></li>
            <li><a href="forum.php">Forum</a></li>
            <li><a href="profile.php">Profil</a></li>
            <li><a href="administration/index.php">Administration</a></li>
            <li><a href="contact.php">Contact</a></li>
            <li><a href="logout.php">Déconnexion</a></li>
HTML;
            } else {
            $this->menu .= <<<HTML
            <li><a href="index.php">Accueil</a></li>
            $categorys
            <li><a href="privatemessages.php">Messages</a></li>
            <li><a href="forum.php">Forum</a></li>
            <li><a href="profile.php">Profil</a></li>
            <li><a href="contact.php">Contact</a></li>
            <li><a href="logout.php">Déconnexion</a></li>
HTML;
            }
        } else {
            $this->menu .= <<<HTML
            <li><a href="index.php">Accueil</a></li>
            $categorys
            <li><a href="forum.php">Forum</a></li>
            <li><a href="connexion.php">Connexion</a></li>
            <li><a href="subscribe.php">Inscription</a></li>
            <li><a href="contact.php">Contact</a></li>
HTML;
        }

        $this->menu .= <<<HTML
                    </ul>
                </div>
        </nav>
HTML;
    }

    public function setAdminMenu(){
        User::startSession();
        $site = Site::getOptions();
        $this->menu = <<<HTML
        <nav class="navbar navbar-default">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="../index.php">{$site['siteName']}</a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
HTML;

        $html = "";
        if($_SESSION['user']->redacArticle || $_SESSION['user']->editOwnArticle || $_SESSION['user']->deleteOwnArticle || $_SESSION['user']->editComment || $_SESSION['user']->deleteComment){
            $html .= "<li><a href='articles.php'>Articles</a></li>\n";
        }

        if($_SESSION['user']->isAdministrator){
            $html .= "<li><a href='categories.php'>Catégories</a></li>\n";
            $html .= "<li><a href='users.php'>Membres</a></li>\n";
        }

        if($_SESSION['user']->isAdministrator){
            $html .= "<li><a href='optionsSite.php'>Options</a></li>\n";
        }

        $this->menu .= $html;

        $this->menu .= <<<HTML
                </ul>
            </div>
        </nav>
HTML;

    }

    public function setFooter(){
        $site = Site::getOptions();
        $this->footer = <<<HTML
        <div class="footer row text-center">
            Tous droits réservés © {$site['siteName']} - Propulsé par <a href="https://github.com/AntoninLefevre/">Antonin Lefevre</a>
        </div>
HTML;
    }


	/**
	 * @access public
	 * @return String
	 */

	public  function toHTML() {
        if (is_null($this->title)) {
            throw new Exception(__CLASS__ . ": title not set") ;
        }
        return <<<HTML
<!doctype html>
<html lang="fr">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{$this->title}</title>
        {$this->head}
    </head>
    <body>
        <div class="container">
            {$this->menu}
            {$this->body}
            {$this->footer}
        </div>
    </body>
</html>
HTML;
	}


}
?>
